# Happy Coding!
service: bot-twitter

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:ENVIRONMENT_NAME}
  region: us-east-1
  environment:
    ENVIRONMENT_NAME: ${self:provider.stage}
    CONSUMER_KEY: ${env:CONSUMER_KEY}
    CONSUMER_SECRET: ${env:CONSUMER_SECRET}
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  twitter:
    handler: src/index.bot
    events:
      - schedule: rate(1 minute)
